# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTypeName', models.CharField(max_length=200)),
                ('DjangoFormat', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'DataType',
            },
        ),
        migrations.CreateModel(
            name='Field_Definition_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field_Definition_MessageName', models.CharField(max_length=200)),
                ('XmlTag', models.CharField(max_length=50)),
                ('LengthMin', models.IntegerField(default=0)),
                ('LengthMax', models.IntegerField(default=0)),
                ('DataType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DataType')),
            ],
            options={
                'db_table': 'Field_Definition_Message',
            },
        ),
        migrations.CreateModel(
            name='LMDM_Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LMDM_FormatName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'LMDM_Format',
            },
        ),
        migrations.CreateModel(
            name='Locate_Message_Definition_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=200)),
                ('Format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LMDM_Format')),
            ],
            options={
                'db_table': 'Locate_Message_Definition_Message',
            },
        ),
        migrations.CreateModel(
            name='Metka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Metka',
            },
        ),
    ]
