# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_std0_dateimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std0',
            name='X',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Z',
            field=models.FloatField(),
        ),
    ]
