# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20160104_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std0',
            name='Battery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='DateImport',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='LabD',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='LocateMessageDefinition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Session',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Status',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Std0',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Tag_ID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Tag_ID_Format',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Timestamp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='X',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='std0',
            name='Zone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
