# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20160104_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metka',
            name='text',
            field=models.TextField(),
        ),
    ]
