# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20160111_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='metka',
            name='DateImport',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
