# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20160112_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='metka',
            name='readed',
            field=models.NullBooleanField(),
        ),
    ]
