# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_metka_readed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommandName', models.CharField(max_length=200)),
                ('ResponseText', models.CharField(max_length=200)),
                ('DateImport', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'LogsJournal',
            },
        ),
    ]
