# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_logsjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='std0',
            name='TimeDelta',
            field=models.IntegerField(default=0),
        ),
    ]
