# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
