# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20160131_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticesBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('Building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Building')),
            ],
            options={
                'db_table': 'VerticesBuilding',
            },
        ),
        migrations.CreateModel(
            name='VerticesFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('Floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Floor')),
            ],
            options={
                'db_table': 'VerticesFloor',
            },
        ),
        migrations.CreateModel(
            name='VerticesKabinet_n_Outer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('Kabinet_n_Outer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Kabinet_n_Outer')),
            ],
            options={
                'db_table': 'VerticesKabinet_n_Outer',
            },
        ),
        migrations.CreateModel(
            name='VerticesWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('Wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Wall')),
            ],
            options={
                'db_table': 'VerticesWall',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='loadlandscape',
            name='landscape_source',
            field=models.FileField(blank=True, null=True, upload_to=b'static/js/webgl/models/<function get_upload_file_name at 0xb64dc9cc>'),
        ),
    ]
