# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20160215_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='maxx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='maxy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='maxz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='minx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='miny',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='minz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='maxx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='maxy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='maxz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='minx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='miny',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='minz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kabinet_n_outer',
            name='maxx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kabinet_n_outer',
            name='maxy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kabinet_n_outer',
            name='maxz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kabinet_n_outer',
            name='minx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kabinet_n_outer',
            name='miny',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kabinet_n_outer',
            name='minz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='maxx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='maxy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='maxz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='minx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='miny',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='minz',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='loadlandscape',
            name='landscape_source',
            field=models.FileField(blank=True, null=True, upload_to=b'static/js/webgl/models/<function get_upload_file_name at 0xb650c9cc>'),
        ),
    ]
