# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20160215_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadlandscape',
            name='landscape_source',
        ),
    ]
