# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20160215_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='LoadLandscape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.LoadLandscape'),
        ),
    ]
