# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20160215_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verticeswall',
            name='Wall',
        ),
        migrations.AddField(
            model_name='verticesbuilding',
            name='LoadLandscape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape'),
        ),
        migrations.AddField(
            model_name='verticesfloor',
            name='LoadLandscape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape'),
        ),
        migrations.AddField(
            model_name='verticeskabinet_n_outer',
            name='LoadLandscape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape'),
        ),
        migrations.DeleteModel(
            name='VerticesWall',
        ),
    ]
