# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20160215_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TagId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TagType', models.CharField(max_length=20, null=True)),
                ('Group', models.CharField(max_length=20, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
    ]
