# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BldChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangeTime', models.DateTimeField(null=True)),
                ('BldNew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Building')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'BldChange',
            },
        ),
        migrations.CreateModel(
            name='FlrChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangeTime', models.DateTimeField(null=True)),
                ('FlrNew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Floor')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'FlrChange',
            },
        ),
        migrations.CreateModel(
            name='KbntChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangeTime', models.DateTimeField(null=True)),
                ('KbntNew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Kabinet_n_Outer')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'KbntChange',
            },
        ),
        migrations.CreateModel(
            name='ZoneChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangeTime', models.DateTimeField(null=True)),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
                ('ZoneNew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape')),
            ],
            options={
                'db_table': 'ZoneChange',
            },
        ),
    ]
