# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_bldchange_flrchange_kbntchange_zonechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadlandscape',
            name='camera_position_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='camera_position_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='camera_position_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='camera_up_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='camera_up_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='camera_up_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='circle_step_symbol',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='dae_rotation_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='dae_rotation_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='dae_rotation_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='get_wall_height_symbol',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='light_target_symbol',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
