# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20160224_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadlandscape',
            name='dae_position_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='dae_position_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loadlandscape',
            name='dae_position_z',
            field=models.FloatField(null=True),
        ),
    ]
