# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20160225_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnOnOffTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OnOff', models.BooleanField()),
                ('OnOffTime', models.DateTimeField(null=True)),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'TurnOnOffTag',
            },
        ),
    ]
