# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20160303_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=200, null=True)),
                ('GeometryMeshesType', models.CharField(max_length=200, null=True)),
                ('GeometryMeshesColor', models.CharField(max_length=50, null=True)),
                ('GeometryMeshesSize', models.CharField(max_length=200, null=True)),
                ('CircleColor', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'TagGroup',
            },
        ),
    ]
