# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20160303_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='TagGroup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
