# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 09:53
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_remove_tag_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggroup',
            old_name='GeometryMeshesColor',
            new_name='MeshColor',
        ),
        migrations.RemoveField(
            model_name='taggroup',
            name='GeometryMeshesSize',
        ),
        migrations.RemoveField(
            model_name='taggroup',
            name='GeometryMeshesType',
        ),
        migrations.AddField(
            model_name='taggroup',
            name='MeshGeometry',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
