# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_taggroup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
                ('TagGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.TagGroup')),
            ],
            options={
                'db_table': 'TagGroup_Tag',
            },
        ),
    ]
