# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_taggroup_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='TagGroup',
        ),
    ]
