# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_remove_tag_tagtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='TagType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TagType'),
            preserve_default=False,
        ),
    ]
