# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_buildingincomezone_floorincomezone_kabinetincomezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'IncomeZone',
            },
        ),
        migrations.CreateModel(
            name='VerticesIncomeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xCoord', models.FloatField()),
                ('yCoord', models.FloatField()),
                ('zCoord', models.FloatField()),
                ('IncomeZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.IncomeZone')),
            ],
            options={
                'db_table': 'VerticesIncomeZone',
            },
        ),
    ]
