# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_incomezone_loadlandscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingincomezone',
            name='IncomeZone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.IncomeZone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorincomezone',
            name='IncomeZone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.IncomeZone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kabinetincomezone',
            name='IncomeZone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.IncomeZone'),
            preserve_default=False,
        ),
    ]
