# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_auto_20160316_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verticesincomezone',
            name='zmax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verticesincomezone',
            name='zmin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
