# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_auto_20160316_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verticesincomezone',
            name='zCoord',
        ),
    ]
