# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_remove_verticesincomezone_zcoord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingExcludeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Building')),
            ],
            options={
                'db_table': 'BuildingExcludeZone',
            },
        ),
        migrations.CreateModel(
            name='ExcludeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoadLandscape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape')),
            ],
            options={
                'db_table': 'ExcludeZone',
            },
        ),
        migrations.CreateModel(
            name='FloorExcludeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExcludeZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ExcludeZone')),
                ('Floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Floor')),
            ],
            options={
                'db_table': 'FloorExcludeZone',
            },
        ),
        migrations.CreateModel(
            name='KabinetExcludeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExcludeZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ExcludeZone')),
                ('Kabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Kabinet_n_Outer')),
            ],
            options={
                'db_table': 'KabinetExcludeZone',
            },
        ),
        migrations.CreateModel(
            name='VerticesExcludeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xCoord', models.FloatField()),
                ('yCoord', models.FloatField()),
                ('zmin', models.FloatField(blank=True, null=True)),
                ('zmax', models.FloatField(blank=True, null=True)),
                ('ExcludeZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ExcludeZone')),
            ],
            options={
                'db_table': 'VerticesExcludeZone',
            },
        ),
        migrations.AddField(
            model_name='buildingexcludezone',
            name='ExcludeZone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ExcludeZone'),
        ),
    ]
