# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0063_auto_20160330_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userzone',
            name='UserZoneName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
