# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_userzone_loadlandscape'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KabinetUzerZone',
            new_name='KabinetUserZone',
        ),
        migrations.AlterModelTable(
            name='kabinetuserzone',
            table='KabinetUserZone',
        ),
    ]
