# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0066_auto_20160331_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flooruserzone',
            old_name='UzerZone',
            new_name='UserZone',
        ),
    ]
