# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0067_auto_20160331_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeZoneUserZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncomeZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.IncomeZone')),
                ('UserZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserZone')),
            ],
            options={
                'db_table': 'IncomeZoneUserZone',
            },
        ),
    ]
