# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_incomezoneuserzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeZoneUserZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExcludeZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ExcludeZone')),
                ('UserZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserZone')),
            ],
            options={
                'db_table': 'ExcludeZoneUserZone',
            },
        ),
    ]
