# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0069_excludezoneuserzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFloorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WriteTime', models.DateTimeField()),
                ('Floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Floor')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'TagFloorOrder',
            },
        ),
        migrations.CreateModel(
            name='TagKabinetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WriteTime', models.DateTimeField()),
                ('Kabinet_n_Outer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Kabinet_n_Outer')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'TagKabinetOrder',
            },
        ),
        migrations.CreateModel(
            name='TagNoUzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WriteTime', models.DateTimeField()),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TagNoUzone',
            },
        ),
        migrations.CreateModel(
            name='TagOutOfBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WriteTime', models.DateTimeField()),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'TagOutOfBuilding',
            },
        ),
        migrations.CreateModel(
            name='TagUzoneUserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WriteTime', models.DateTimeField()),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('UserZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserZone')),
            ],
            options={
                'db_table': 'TagUzoneUserOrder',
            },
        ),
    ]
