# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0073_tagnouzone_loadlandscape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Object',
            },
        ),
        migrations.CreateModel(
            name='ObjectLoadLandscape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoadLandscape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape')),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Object')),
            ],
            options={
                'db_table': 'ObjectLoadLandscape',
            },
        ),
        migrations.CreateModel(
            name='ObjectObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Object')),
            ],
            options={
                'db_table': 'ObjectObjectType',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ObjectType',
            },
        ),
        migrations.AddField(
            model_name='objectobjecttype',
            name='ObjectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ObjectType'),
        ),
    ]
