# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0074_auto_20160419_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='xCoord',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='yCoord',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='zCoord',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
