# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0075_auto_20160419_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectloadlandscape',
            name='LoadLandscape',
        ),
        migrations.RemoveField(
            model_name='objectloadlandscape',
            name='Object',
        ),
        migrations.AddField(
            model_name='object',
            name='LoadLandscape',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ObjectLoadLandscape',
        ),
    ]
