# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0077_groupuserzone_loadlandscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='Command',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
