# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0078_objecttype_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_idLayer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_inUse',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='object',
            name='server_minNumPoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='server_z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
