# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0079_auto_20160420_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='server_description',
        ),
        migrations.RemoveField(
            model_name='object',
            name='server_idLayer',
        ),
        migrations.RemoveField(
            model_name='object',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='object',
            name='server_x',
        ),
        migrations.RemoveField(
            model_name='object',
            name='server_y',
        ),
        migrations.RemoveField(
            model_name='object',
            name='server_z',
        ),
    ]
