# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0080_auto_20160421_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadlandscape',
            name='landscape_source',
            field=models.FileField(blank=True, null=True, upload_to=b'<function get_upload_file_name at 0xb65df09c>'),
        ),
        migrations.AlterField(
            model_name='object',
            name='server_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
