# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0082_auto_20160422_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='CommandList',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
