# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0083_objecttype_commandlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadlandscape',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
