# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0084_loadlandscape_server_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='LoadLandscape',
        ),
    ]
