# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0086_object_loadlandscape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='LoadLandscape',
        ),
        migrations.RemoveField(
            model_name='objectobjecttype',
            name='Object',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
