# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0087_auto_20160422_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectobjecttype',
            name='ObjectType',
        ),
        migrations.DeleteModel(
            name='ObjectObjectType',
        ),
    ]
