# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0088_auto_20160422_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectType',
        ),
    ]
