# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0089_delete_objecttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('xCoord', models.FloatField()),
                ('yCoord', models.FloatField()),
                ('zCoord', models.FloatField()),
                ('server_id', models.CharField(blank=True, max_length=200, null=True)),
                ('server_inUse', models.NullBooleanField()),
                ('server_type', models.CharField(blank=True, max_length=1, null=True)),
                ('server_radius', models.FloatField(blank=True, null=True)),
                ('server_minNumPoints', models.IntegerField(blank=True, null=True)),
                ('LoadLandscape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape')),
            ],
            options={
                'db_table': 'Object',
            },
        ),
        migrations.CreateModel(
            name='ObjectObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Object')),
            ],
            options={
                'db_table': 'ObjectObjectType',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Command', models.CharField(blank=True, max_length=200, null=True)),
                ('CommandList', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ObjectType',
            },
        ),
        migrations.AddField(
            model_name='objectobjecttype',
            name='ObjectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ObjectType'),
        ),
    ]
