# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0090_auto_20160422_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='CommandDelete',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
