# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0092_objectbuilding_objectfloor_objectkabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='CommandUpdate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
