# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0093_objecttype_commandupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='Name_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
