# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0095_command_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height1', models.FloatField(blank=True, null=True)),
                ('height2', models.FloatField(blank=True, null=True)),
                ('ws_id', models.IntegerField(blank=True, null=True)),
                ('latitude1', models.FloatField(blank=True, null=True)),
                ('latitude2', models.FloatField(blank=True, null=True)),
                ('longitude1', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('scaleX', models.FloatField(blank=True, null=True)),
                ('scaleY', models.FloatField(blank=True, null=True)),
                ('x1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('y1', models.FloatField(blank=True, null=True)),
                ('y2', models.FloatField(blank=True, null=True)),
                ('z1', models.FloatField(blank=True, null=True)),
                ('z2', models.FloatField(blank=True, null=True)),
                ('server_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('sizeX', models.FloatField(blank=True, null=True)),
                ('sizeY', models.FloatField(blank=True, null=True)),
                ('sizeZ', models.FloatField(blank=True, null=True)),
                ('angleRotateX', models.FloatField(blank=True, null=True)),
                ('angleRotateY', models.FloatField(blank=True, null=True)),
                ('angleRotateZ', models.FloatField(blank=True, null=True)),
                ('objType', models.FloatField(blank=True, null=True)),
                ('server_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlanTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_id', models.IntegerField(blank=True, null=True)),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('ws_parent_id', models.IntegerField(blank=True, null=True)),
                ('server_parent_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='idLayer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='inuse',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='server_idLayer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionplantree',
            name='Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Session'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Session'),
        ),
        migrations.AddField(
            model_name='sessionlayer',
            name='Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Session'),
        ),
    ]
