# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0097_auto_20160427_1633'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sessiontable',
            table='SessionTable',
        ),
    ]
