# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0098_auto_20160427_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionlayer',
            old_name='Session',
            new_name='SessionTable',
        ),
        migrations.RenameField(
            model_name='sessionplan',
            old_name='Session',
            new_name='SessionTable',
        ),
        migrations.RenameField(
            model_name='sessionplantree',
            old_name='Session',
            new_name='SessionTable',
        ),
        migrations.AlterModelTable(
            name='sessionlayer',
            table='SessionLayer',
        ),
        migrations.AlterModelTable(
            name='sessionplan',
            table='SessionPlan',
        ),
        migrations.AlterModelTable(
            name='sessionplantree',
            table='SessionPlanTree',
        ),
    ]
