# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0099_auto_20160427_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlayer',
            name='longitude2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
