# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0100_sessionlayer_longitude2'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='LoadLandscape2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
