# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0141_userzone_loadlandscape2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userzone',
            name='LoadLandscape',
        ),
    ]
