# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0168_remove_sessiontable_loadlandscape2'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadlandscape',
            name='session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
