# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0169_loadlandscape_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('server_id', models.BigIntegerField()),
                ('server_id_hex', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Node',
            },
        ),
    ]
