# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0172_auto_20160512_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='server_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='server_id_hex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
