# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0173_auto_20160512_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='server_id_hex',
            new_name='id_hex',
        ),
    ]
