# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0174_auto_20160512_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='id_hex',
        ),
    ]
