# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0175_remove_node_id_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterName', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'CorrectionFilter',
            },
        ),
        migrations.CreateModel(
            name='LocationMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterName', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'LocationMethods',
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterName', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='TagCorrectionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(blank=True, max_length=200, null=True)),
                ('CorrectionFilter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CorrectionFilter')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'TagCorrectionFilter',
            },
        ),
        migrations.CreateModel(
            name='TagLocationMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationMethods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LocationMethods')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'TagLocationMethods',
            },
        ),
        migrations.CreateModel(
            name='TagSensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sensors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Sensors')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'TagSensors',
            },
        ),
        migrations.CreateModel(
            name='TagTimeUpdateLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(blank=True, max_length=200, null=True)),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag')),
            ],
            options={
                'db_table': 'TagTimeUpdateLocation',
            },
        ),
        migrations.CreateModel(
            name='TimeUpdateLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParameterName', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'TimeUpdateLocation',
            },
        ),
        migrations.AddField(
            model_name='tagtimeupdatelocation',
            name='TimeUpdateLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.TimeUpdateLocation'),
        ),
    ]
