# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0177_tag_registred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Registred',
            new_name='Registered',
        ),
    ]
