# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0178_auto_20160516_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionfilter',
            name='ParameterValueType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
