# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0179_correctionfilter_parametervaluetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('xCoord', models.FloatField(blank=True, null=True)),
                ('yCoord', models.FloatField(blank=True, null=True)),
                ('zCoord', models.FloatField(blank=True, null=True)),
                ('LoadLandscape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LoadLandscape')),
            ],
            options={
                'db_table': 'Point',
            },
        ),
        migrations.CreateModel(
            name='PointBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Building')),
                ('Point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Point')),
            ],
            options={
                'db_table': 'PointBuilding',
            },
        ),
        migrations.CreateModel(
            name='PointFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Floor')),
                ('Point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Point')),
            ],
            options={
                'db_table': 'PointFloor',
            },
        ),
        migrations.CreateModel(
            name='PointKabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Kabinet_n_Outer')),
                ('Point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Point')),
            ],
            options={
                'db_table': 'PointKabinet',
            },
        ),
    ]
