# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0182_auto_20160520_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Qparameter',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Parameters', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Query',
            },
        ),
        migrations.CreateModel(
            name='QueryQparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qparameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Qparameter')),
                ('Query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Query')),
            ],
            options={
                'db_table': 'QueryQparameter',
            },
        ),
    ]
