# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0183_qparameter_query_queryqparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='qparameter',
            name='keyName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
