# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0184_qparameter_keyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qparameter',
            old_name='keyName',
            new_name='KeyName',
        ),
    ]
