# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0185_auto_20160524_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointBeenCalibrated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Cpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Cpoint')),
            ],
            options={
                'db_table': 'PointBeenCalibrated',
            },
        ),
    ]
