# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0186_pointbeencalibrated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointbeencalibrated',
            old_name='Data',
            new_name='Date',
        ),
    ]
