# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportparameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportParameters',
            new_name='ReportParameter',
        ),
    ]
