# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20160411_0917'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parameter',
            table='Parameter',
        ),
        migrations.AlterModelTable(
            name='reportparameter',
            table='ReportParameter',
        ),
    ]
