# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_parameter_domname'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='CanBeMultipleTagId',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
