# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_report_canbemultipletagid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TemplateParameter', models.CharField(max_length=200)),
                ('TemplateFileName', models.CharField(max_length=200)),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
            options={
                'db_table': 'ReportStructure',
            },
        ),
        migrations.CreateModel(
            name='ReportUzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TemplateParameter', models.CharField(max_length=200)),
                ('TemplateFileName', models.CharField(max_length=200)),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
            options={
                'db_table': 'ReportUzone',
            },
        ),
    ]
